#ifndef BINARY_OPERATORS_H
#define BINARY_OPERATORS_H
#include <parser/parser.h>

const char *binary_operator_outputs[OT_TYPE_COUNT][OP_TYPE_COUNT] = {
	[OT_INT][OP_ADD] = "leal\t(%rsi,%rdi), %eax",
	[OT_INT][OP_SUB] = "movq\t%rdi, %rax\n\tsubl\t%esi, %eax",
	[OT_INT][OP_MUL] = "movq\t%rsi, %rax\n\timull\t%edi, %eax",
	[OT_INT][OP_DIV] = "movq\t%rdi, %rax\n\tcltd\n\tidivl\t%esi",
	[OT_INT][OP_MOD] = "movq\t%rdi, %rax\n\tcltd\n\tidivl\t%esi\n\tmovl\t%edx, %eax",
	[OT_INT][OP_BXOR] = "movq\t%rsi, %rax\n\txorl\t%edi, %eax",
	[OT_INT][OP_BOR] = "movq\t%rsi, %rax\n\torl\t%edi, %eax",
	[OT_INT][OP_BAND] = "movq\t%rdi, %rax\n\tandl\t%esi, %eax",
	[OT_INT][OP_LSHIFT] = "movq\t%rsi, %rcx\n\tmovq\t%rdi, %rax\t\nshll\t%cl, %eax",
	[OT_INT][OP_RSHIFT] = "movq\t%rsi, %rcx\n\tmovq\t%rdi, %rax\t\nsarl\t%cl, %eax",
	[OT_INT][OP_LESS] = "xorl\t%eax, %eax\n\tcmpl\t%esi, %edi\n\tsetl\t%al",
	[OT_INT][OP_GREATER] = "xorl\t%eax, %eax\n\tcmpl\t%esi, %edi\n\tsetg\t%al",
	[OT_INT][OP_LESS_EQ] = "xorl\t%eax, %eax\n\tcmpl\t%esi, %edi\n\tsetle\t%al",
	[OT_INT][OP_GREATER_EQ] = "xorl\t%eax, %eax\n\tcmpl\t%esi, %edi\n\tsetge\t%al",
	[OT_INT][OP_EQUAL] = "xorl\t%eax, %eax\n\tcmpl\t%esi, %edi\n\tsete\t%al",
	[OT_INT][OP_NOT_EQUAL] = "xorl\t%eax, %eax\n\tcmpl\t%esi, %edi\n\tsetne\t%al",
	[OT_UINT][OP_ADD] = "leal\t(%rsi,%rdi), %eax",
	[OT_UINT][OP_SUB] = "movq\t%rdi, %rax\n\tsubl\t%esi, %eax",
	[OT_UINT][OP_MUL] = "movq\t%rsi, %rax\n\timull\t%edi, %eax",
	[OT_UINT][OP_DIV] = "movq\t%rdi, %rax\n\txorl\t%edx, %edx\n\tdivl\t%esi",
	[OT_UINT][OP_MOD] = "movq\t%rdi, %rax\n\txorl\t%edx, %edx\n\tdivl\t%esi\n\tmovl\t%edx, %eax",
	[OT_UINT][OP_BXOR] = "movq\t%rsi, %rax\n\txorl\t%edi, %eax",
	[OT_UINT][OP_BOR] = "movq\t%rsi, %rax\n\torl\t%edi, %eax",
	[OT_UINT][OP_BAND] = "movq\t%rdi, %rax\n\tandl\t%esi, %eax",
	[OT_UINT][OP_LSHIFT] = "movq\t%rsi, %rcx\n\tmovq\t%rdi, %rax\n\tshll\t%cl, %eax",
	[OT_UINT][OP_RSHIFT] = "movq\t%rsi, %rcx\n\tmovq\t%rdi, %rax\n\tshrl\t%cl, %eax",
	[OT_UINT][OP_LESS] = "xorl\t%eax, %eax\n\tcmpl\t%esi, %edi\n\tsetb\t%al",
	[OT_UINT][OP_GREATER] = "xorl\t%eax, %eax\n\tcmpl\t%esi, %edi\n\tseta\t%al",
	[OT_UINT][OP_LESS_EQ] = "xorl\t%eax, %eax\n\tcmpl\t%esi, %edi\n\tsetbe\t%al",
	[OT_UINT][OP_GREATER_EQ] = "xorl\t%eax, %eax\n\tcmpl\t%esi, %edi\n\tsetae\t%al",
	[OT_UINT][OP_EQUAL] = "xorl\t%eax, %eax\n\tcmpl\t%esi, %edi\n\tsete\t%al",
	[OT_UINT][OP_NOT_EQUAL] = "xorl\t%eax, %eax\n\tcmpl\t%esi, %edi\n\tsetne\t%al",
	[OT_LONG][OP_ADD] = "leaq\t(%rdi,%rsi), %rax",
	[OT_LONG][OP_SUB] = "movq\t%rdi, %rax\n\tsubq\t%rsi, %rax",
	[OT_LONG][OP_MUL] = "movq\t%rdi, %rax\n\timulq\t%rsi, %rax",
	[OT_LONG][OP_DIV] = "movq\t%rdi, %rax\n\tcqto\n\tidivq\t%rsi",
	[OT_LONG][OP_MOD] = "movq\t%rdi, %rax\n\tcqto\n\tidivq\t%rsi\n\tmovq\t%rdx, %rax",
	[OT_LONG][OP_BXOR] = "movq\t%rdi, %rax\n\txorq\t%rsi, %rax",
	[OT_LONG][OP_BOR] = "movq\t%rdi, %rax\n\torq\t%rsi, %rax",
	[OT_LONG][OP_BAND] = "movq\t%rdi, %rax\n\tandq\t%rsi, %rax",
	[OT_LONG][OP_LSHIFT] = "movq\t%rsi, %rcx\n\tmovq\t%rdi, %rax\n\tshlq\t%cl, %rax",
	[OT_LONG][OP_RSHIFT] = "movq\t%rsi, %rcx\n\tmovq\t%rdi, %rax\n\tsarq\t%cl, %rax",
	[OT_LONG][OP_LESS] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetl\t%al",
	[OT_LONG][OP_GREATER] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetg\t%al",
	[OT_LONG][OP_LESS_EQ] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetle\t%al",
	[OT_LONG][OP_GREATER_EQ] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetge\t%al",
	[OT_LONG][OP_EQUAL] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsete\t%al",
	[OT_LONG][OP_NOT_EQUAL] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetne\t%al",
	[OT_ULONG][OP_ADD] = "leaq\t(%rdi,%rsi), %rax",
	[OT_ULONG][OP_SUB] = "movq\t%rdi, %rax\n\tsubq\t%rsi, %rax",
	[OT_ULONG][OP_MUL] = "movq\t%rdi, %rax\n\timulq\t%rsi, %rax",
	[OT_ULONG][OP_DIV] = "movq\t%rdi, %rax\n\txorl\t%edx, %edx\n\tdivq\t%rsi",
	[OT_ULONG][OP_MOD] = "movq\t%rdi, %rax\n\txorl\t%edx, %edx\n\tdivq\t%rsi\n\tmovq\t%rdx, %rax",
	[OT_ULONG][OP_BXOR] = "movq\t%rdi, %rax\n\txorq\t%rsi, %rax",
	[OT_ULONG][OP_BOR] = "movq\t%rdi, %rax\n\torq\t%rsi, %rax",
	[OT_ULONG][OP_BAND] = "movq\t%rdi, %rax\n\tandq\t%rsi, %rax",
	[OT_ULONG][OP_LSHIFT] = "movq\t%rsi, %rcx\n\tmovq\t%rdi, %rax\n\tshlq\t%cl, %rax",
	[OT_ULONG][OP_RSHIFT] = "movq\t%rsi, %rcx\n\tmovq\t%rdi, %rax\n\tshrq\t%cl, %rax",
	[OT_ULONG][OP_LESS] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetb\t%al",
	[OT_ULONG][OP_GREATER] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tseta\t%al",
	[OT_ULONG][OP_LESS_EQ] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetbe\t%al",
	[OT_ULONG][OP_GREATER_EQ] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetae\t%al",
	[OT_ULONG][OP_EQUAL] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsete\t%al",
	[OT_ULONG][OP_NOT_EQUAL] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetne\t%al",
	[OT_LLONG][OP_ADD] = "leaq\t(%rdi,%rsi), %rax",
	[OT_LLONG][OP_SUB] = "movq\t%rdi, %rax\n\tsubq\t%rsi, %rax",
	[OT_LLONG][OP_MUL] = "movq\t%rdi, %rax\n\timulq\t%rsi, %rax",
	[OT_LLONG][OP_DIV] = "movq\t%rdi, %rax\n\tcqto\n\tidivq\t%rsi",
	[OT_LLONG][OP_MOD] = "movq\t%rdi, %rax\n\tcqto\n\tidivq\t%rsi\n\tmovq\t%rdx, %rax",
	[OT_LLONG][OP_BXOR] = "movq\t%rdi, %rax\n\txorq\t%rsi, %rax",
	[OT_LLONG][OP_BOR] = "movq\t%rdi, %rax\n\torq\t%rsi, %rax",
	[OT_LLONG][OP_BAND] = "movq\t%rdi, %rax\n\tandq\t%rsi, %rax",
	[OT_LLONG][OP_LSHIFT] = "movq\t%rsi, %rcx\n\tmovq\t%rdi, %rax\n\tshlq\t%cl, %rax",
	[OT_LLONG][OP_RSHIFT] = "movq\t%rsi, %rcx\n\tmovq\t%rdi, %rax\n\tsarq\t%cl, %rax",
	[OT_LLONG][OP_LESS] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetl\t%al",
	[OT_LLONG][OP_GREATER] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetg\t%al",
	[OT_LLONG][OP_LESS_EQ] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetle\t%al",
	[OT_LLONG][OP_GREATER_EQ] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetge\t%al",
	[OT_LLONG][OP_EQUAL] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsete\t%al",
	[OT_LLONG][OP_NOT_EQUAL] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetne\t%al",
	[OT_ULLONG][OP_ADD] = "leaq\t(%rdi,%rsi), %rax",
	[OT_ULLONG][OP_SUB] = "movq\t%rdi, %rax\n\tsubq\t%rsi, %rax",
	[OT_ULLONG][OP_MUL] = "movq\t%rdi, %rax\n\timulq\t%rsi, %rax",
	[OT_ULLONG][OP_DIV] = "movq\t%rdi, %rax\n\txorl\t%edx, %edx\n\tdivq\t%rsi",
	[OT_ULLONG][OP_MOD] = "movq\t%rdi, %rax\n\txorl\t%edx, %edx\n\tdivq\t%rsi\n\tmovq\t%rdx, %rax",
	[OT_ULLONG][OP_BXOR] = "movq\t%rdi, %rax\n\txorq\t%rsi, %rax",
	[OT_ULLONG][OP_BOR] = "movq\t%rdi, %rax\n\torq\t%rsi, %rax",
	[OT_ULLONG][OP_BAND] = "movq\t%rdi, %rax\n\tandq\t%rsi, %rax",
	[OT_ULLONG][OP_LSHIFT] = "movq\t%rsi, %rcx\n\tmovq\t%rdi, %rax\n\tshlq\t%cl, %rax",
	[OT_ULLONG][OP_RSHIFT] = "movq\t%rsi, %rcx\n\tmovq\t%rdi, %rax\n\tshrq\t%cl, %rax",
	[OT_ULLONG][OP_LESS] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetb\t%al",
	[OT_ULLONG][OP_GREATER] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tseta\t%al",
	[OT_ULLONG][OP_LESS_EQ] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetbe\t%al",
	[OT_ULLONG][OP_GREATER_EQ] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetae\t%al",
	[OT_ULLONG][OP_EQUAL] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsete\t%al",
	[OT_ULLONG][OP_NOT_EQUAL] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetne\t%al",
	[OT_FLOAT][OP_ADD] = "movd\t%edi, %xmm0\n\tmovd\t%esi, %xmm1\n\taddss\t%xmm0, %xmm1\n\tmovd\t%xmm1, %eax",
	[OT_FLOAT][OP_SUB] = "movd\t%edi, %xmm0\n\tmovd\t%esi, %xmm1\n\tsubss\t%xmm1, %xmm0\n\tmovd\t%xmm0, %eax",
	[OT_FLOAT][OP_MUL] = "movd\t%edi, %xmm0\n\tmovd\t%esi, %xmm1\n\tmulss\t%xmm0, %xmm1\n\tmovd\t%xmm1, %eax",
	[OT_FLOAT][OP_DIV] = "movd\t%edi, %xmm0\n\tmovd\t%esi, %xmm1\n\tdivss\t%xmm1, %xmm0\n\tmovd\t%xmm0, %eax",
	/* [OT_FLOAT][OP_MOD] = "", */
	/* [OT_FLOAT][OP_BXOR] = "", */
	/* [OT_FLOAT][OP_BOR] = "", */
	/* [OT_FLOAT][OP_BAND] = "", */
	/* [OT_FLOAT][OP_LSHIFT] = "", */
	/* [OT_FLOAT][OP_RSHIFT] = "", */
	[OT_FLOAT][OP_LESS] = "movd\t%edi, %xmm0\n\tmovd\t%esi, %xmm1\n\txorl\t%eax, %eax\n\tucomiss\t%xmm0, %xmm1\n\tseta\t%al",
	[OT_FLOAT][OP_GREATER] = "movd\t%edi, %xmm0\n\tmovd\t%esi, %xmm1\n\txorl\t%eax, %eax\n\tucomiss\t%xmm1, %xmm0\n\tseta\t%al",
	[OT_FLOAT][OP_LESS_EQ] = "movd\t%edi, %xmm0\n\tmovd\t%esi, %xmm1\n\txorl\t%eax, %eax\n\tucomiss\t%xmm0, %xmm1\n\tsetae\t%al",
	[OT_FLOAT][OP_GREATER_EQ] = "movd\t%edi, %xmm0\n\tmovd\t%esi, %xmm1\n\txorl\t%eax, %eax\n\tucomiss\t%xmm1, %xmm0\n\tsetae\t%al",
	[OT_FLOAT][OP_EQUAL] = "movd\t%edi, %xmm0\n\tmovd\t%esi, %xmm1\n\tcmpeqss\t%xmm0, %xmm1\n\tmovd\t%xmm1, %eax\n\tandl\t$1, %eax",
	[OT_FLOAT][OP_NOT_EQUAL] = "movd\t%edi, %xmm0\n\tmovd\t%esi, %xmm1\n\tcmpneqss\t%xmm0, %xmm1\n\tmovd\t%xmm1, %eax\n\tandl\t$1, %eax",
	[OT_DOUBLE][OP_ADD] = "movq\t%rdi, %xmm0\n\tmovq\t%rsi, %xmm1\n\taddsd\t%xmm0, %xmm1\n\tmovq\t%xmm1, %rax",
	[OT_DOUBLE][OP_SUB] = "movq\t%rdi, %xmm0\n\tmovq\t%rsi, %xmm1\n\tsubsd\t%xmm1, %xmm0\n\tmovq\t%xmm0, %rax",
	[OT_DOUBLE][OP_MUL] = "movq\t%rdi, %xmm0\n\tmovq\t%rsi, %xmm1\n\tmulsd\t%xmm0, %xmm1\n\tmovq\t%xmm1, %rax",
	[OT_DOUBLE][OP_DIV] = "movq\t%rdi, %xmm0\n\tmovq\t%rsi, %xmm1\n\tdivsd\t%xmm1, %xmm0\n\tmovq\t%xmm0, %rax",
	/* [OT_DOUBLE][OP_MOD] = "", */
	/* [OT_DOUBLE][OP_BXOR] = "", */
	/* [OT_DOUBLE][OP_BOR] = "", */
	/* [OT_DOUBLE][OP_BAND] = "", */
	/* [OT_DOUBLE][OP_LSHIFT] = "", */
	/* [OT_DOUBLE][OP_RSHIFT] = "", */
	[OT_DOUBLE][OP_LESS] = "movq\t%rdi, %xmm0\n\tmovq\t%rsi, %xmm1\n\txorl\t%eax, %eax\n\tucomisd\t%xmm0, %xmm1\n\tseta\t%al",
	[OT_DOUBLE][OP_GREATER] = "movq\t%rdi, %xmm0\n\tmovq\t%rsi, %xmm1\n\txorl\t%eax, %eax\n\tucomisd\t%xmm1, %xmm0\n\tseta\t%al",
	[OT_DOUBLE][OP_LESS_EQ] = "movq\t%rdi, %xmm0\n\tmovq\t%rsi, %xmm1\n\txorl\t%eax, %eax\n\tucomisd\t%xmm0, %xmm1\n\tsetae\t%al",
	[OT_DOUBLE][OP_GREATER_EQ] = "movq\t%rdi, %xmm0\n\tmovq\t%rsi, %xmm1\n\txorl\t%eax, %eax\n\tucomisd\t%xmm1, %xmm0\n\tsetae\t%al",
	[OT_DOUBLE][OP_EQUAL] = "movq\t%rdi, %xmm0\n\tmovq\t%rsi, %xmm1\n\tcmpeqsd\t%xmm0, %xmm1\n\tmovq\t%xmm1, %rax\n\tandl\t$1, %eax",
	[OT_DOUBLE][OP_NOT_EQUAL] = "movq\t%rdi, %xmm0\n\tmovq\t%rsi, %xmm1\n\tcmpneqsd\t%xmm0, %xmm1\n\tmovq\t%xmm1, %rax\n\tandl\t$1, %eax",
	/* [OT_PTR][OP_ADD] = "", */
	/* [OT_PTR][OP_SUB] = "", */
	/* [OT_PTR][OP_MUL] = "", */
	/* [OT_PTR][OP_DIV] = "", */
	/* [OT_PTR][OP_MOD] = "", */
	/* [OT_PTR][OP_BXOR] = "", */
	/* [OT_PTR][OP_BOR] = "", */
	/* [OT_PTR][OP_BAND] = "", */
	/* [OT_PTR][OP_LSHIFT] = "", */
	/* [OT_PTR][OP_RSHIFT] = "", */
	[OT_PTR][OP_LESS] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetb\t%al",
	[OT_PTR][OP_GREATER] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tseta\t%al",
	[OT_PTR][OP_LESS_EQ] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetbe\t%al",
	[OT_PTR][OP_GREATER_EQ] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetae\t%al",
	[OT_PTR][OP_EQUAL] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsete\t%al",
	[OT_PTR][OP_NOT_EQUAL] = "xorl\t%eax, %eax\n\tcmpq\t%rsi, %rdi\n\tsetne\t%al",
};

#endif
